name: coa_project
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.5.0
  adaptive_components: ^0.0.9
  google_fonts: ^4.0.3
  font_awesome_flutter: ^10.4.0
  flutter_rating_bar: ^4.0.1
  intl: ^0.17.0
  animations: ^2.0.7
  flutter_datetime_picker: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.19

flutter_native_splash:
  color: '#ffffff'
  image: 'assets/images/main_splash.png'
  color_dark: '#262626'
  image_dark: 'assets/images/main_splash.png'
  fullscreen: true
  android_12:
    icon_background_color: '#ffffff'
    image: 'assets/images/main_splash.png'
    icon_background_color_dark: '#262626'
    image_dark: 'assets/images/main_splash.png'

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/design_course/
    - assets/fitness_app/
    - assets/hotel/
    - assets/introduction_animation/

  fonts:
        - family: WorkSans
          fonts:
              - asset: assets/fonts/WorkSans-Regular.ttf
              - asset: assets/fonts/WorkSans-Medium.ttf
                weight: 500
              - asset: assets/fonts/WorkSans-SemiBold.ttf
                weight: 600
              - asset: assets/fonts/WorkSans-Bold.ttf
                weight: 700
        - family: Roboto
          fonts:
              - asset: assets/fonts/Roboto-Bold.ttf
              - asset: assets/fonts/Roboto-Regular.ttf
              - asset: assets/fonts/Roboto-Medium.ttf
                weight: 400