name: coa_project
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: 
  firebase_core: 
  firebase_auth: 
  cloud_firestore: 
  adaptive_components: 
  google_fonts: 
  font_awesome_flutter: 
  flutter_rating_bar: 
  intl: 
  animations: 
  flutter_datetime_picker:
  flip_card: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.19

flutter_native_splash:
  color: '#ffffff'
  image: 'assets/images/main_splash.png'
  color_dark: '#213333'
  image_dark: 'assets/images/main_splash.png'
  fullscreen: true
  android_12:
    icon_background_color: '#ffffff'
    image: 'assets/images/main_splash.png'
    icon_background_color_dark: '#213333'
    image_dark: 'assets/images/main_splash.png'

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/introduction_animation/

  fonts:
        - family: WorkSans
          fonts:
              - asset: assets/fonts/WorkSans-Regular.ttf
              - asset: assets/fonts/WorkSans-Medium.ttf
                weight: 500
              - asset: assets/fonts/WorkSans-SemiBold.ttf
                weight: 600
              - asset: assets/fonts/WorkSans-Bold.ttf
                weight: 700
        - family: Roboto
          fonts:
              - asset: assets/fonts/Roboto-Bold.ttf
              - asset: assets/fonts/Roboto-Regular.ttf
              - asset: assets/fonts/Roboto-Medium.ttf
                weight: 400