// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1poZOo05iwk3nuMHgMqQmZ9zRp0DlogM',
    appId: '1:604754175630:web:4bb847f14240cd2cd4cbdf',
    messagingSenderId: '604754175630',
    projectId: 'coa-project-2d439',
    authDomain: 'coa-project-2d439.firebaseapp.com',
    storageBucket: 'coa-project-2d439.appspot.com',
    measurementId: 'G-Q2CVWL4SBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt8suModuIzBYfwPuoSW4DeDjzjFBJAIE',
    appId: '1:604754175630:android:8fcff77e4f508873d4cbdf',
    messagingSenderId: '604754175630',
    projectId: 'coa-project-2d439',
    storageBucket: 'coa-project-2d439.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy1TVEGU7g1ZxioFnz_MuFmHy_tl0NbHA',
    appId: '1:604754175630:ios:5f847d11dc22a2d3d4cbdf',
    messagingSenderId: '604754175630',
    projectId: 'coa-project-2d439',
    storageBucket: 'coa-project-2d439.appspot.com',
    iosClientId: '604754175630-bevb07dp0n97jjt38f7r43pbc7b7esnk.apps.googleusercontent.com',
    iosBundleId: 'com.ethan.coa',
  );
}
